In [133]:
from pandas import read_csv, Series, DataFrame, concat
import numpy as np
import pathlib
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score

In [92]:
#Number of recommendations set to 20
no_recom = 20
games_data = read_csv('processed_games_for_content-based.csv')
users_data = read_csv('Content_Training_Testing/content_user_train.csv')
#Getting reviews information from the csv generated
games_review = read_csv('steam_games_review.csv', usecols=["name", "positive_review_percent"])
#Creating reverse map of indices and game names
games_indices = Series(games_data.index, index=games_data["name"]).drop_duplicates()
#Getting list of all unique games we have in games dataset
games_list = games_data['name'].unique()
#Creating new dataframe for recommendation
df_rec = list(map(str, range(1, no_recom+1)))
df_new = list(map(str, range(1, no_recom+1)))
df_rec = ["user_id"] + df_rec
df_new = ["user_id"] + df_new

In [160]:
#Total unique games in training dataset
users_data.game.nunique()

4884

In [93]:
#Recommendation functions
#Function taking game titles (game name) and cosine similarity as input arguments and returns most similar games
def make_recommendation_by_sim(game_title, cosine_sim):
    if game_title not in games_list:
        return []
    #Index of the game that matches the name
    id = games_indices[game_title]
    if type(id) is Series:
        return []
    #Calculating pairwise similarity scores of all games with the game mentioned
    similarity_score = list(enumerate(cosine_sim[id]))
    similarity_score = sorted(similarity_score, key=lambda x: x[1], reverse=True)
    #Getting similarity scores of top 20 most similar games
    similarity_score = similarity_score[1:no_recom+1]
    #Getting game indices of the above 20 games with matching scores
    games_id =  [i[0] for i in similarity_score]
    #finally returning top most similar games
    return games_data['name'].iloc[games_id].tolist()


In [94]:
#Function taking user id , games user have and the games user already have as input 
#and making recommendations
def make_recommendation_for_user(user_id, game_list, games_of_user):
    if type(game_list) is not list or len(game_list) == 0:
        return DataFrame(data=[[user_id]+[""] * no_recom], columns=df_rec)
    recom_reviews = games_review.loc[games_review['name'].isin(game_list)]
    recom_reviews = recom_reviews.loc[~recom_reviews['name'].isin(games_of_user)]
    recom_reviews = recom_reviews.sort_values(by='positive_review_percent', ascending=False)
    if len(recom_reviews) < no_recom:
        return DataFrame(data=[[user_id] + recom_reviews["name"].tolist() + [""] * (no_recom - len(recom_reviews.index))], columns=df_rec)
    else:
        return DataFrame(data=[[user_id] + recom_reviews["name"].tolist()[0:no_recom]], columns=df_rec)
    

In [210]:
#Function to generate recommendation for a user by a column feature
def make_recommendation_bycolumn(column_name, user_id):
    recom_by_userdata = DataFrame(columns=df_rec)
    games_data[column_name] = games_data[column_name].fillna('')
    #Calculating Cosine Similarity Matrix using the column feature
    count =  CountVectorizer(stop_words='english')
    count_matrix = count.fit_transform(games_data[column_name])
    similarity_matrix = cosine_similarity(count_matrix, count_matrix)
    #print(similarity_matrix)
    id = ''
    suggestion_list = list()
    games_user_has_list = list()
    for i, row in users_data.iterrows():
       if row["user_id"] == user_id:   
         recom_by_userdata = concat([recom_by_userdata, make_recommendation_for_user(user_id, suggestion_list, games_user_has_list)])  
         games_user_has_list.extend([row["game"]])
         suggestion_list.extend(make_recommendation_by_sim(row["game"], similarity_matrix))
         break
    recom_by_userdata = concat([recom_by_userdata, make_recommendation_for_user(user_id, suggestion_list, games_user_has_list)], ignore_index=True)
    return recom_by_userdata

In [211]:
df_1 = make_recommendation_bycolumn('popular_tags', 5250)
df_1

user_id              1                2         3       4  \
0    5250                                                     
1    5250  Killing Floor  Team Fortress 2  Warframe  Arma 3   

                                        5                    6  \
0                                                                
1  Earth Defense Force: Insect Armageddon  Natural Selection 2   

                                   7                     8  \
0                                                            
1  Tom Clancy's Rainbow Six® Vegas 2  Halo: Spartan Strike   

                                                   9  ...              11  \
0                                                     ...                   
1  Resident Evil Revelations / Biohazard Revelations  ...  Primal Carnage   

                       12        13              14                   15  \
0                                                                          
1  Alien Breed 2: Assault  Defiance  ORION: Prelude  Alien Breed: Impact   

                       16                          17        18  \
0                                                                 
1  Alien Breed 3: Descent  Primal Carnage: Extinction  God Mode   

                  19          20  
0                                 
1  Scourge: Outbreak  Dark Void™  

[2 rows x 21 columns]

In [167]:
make_recommendation_bycolumn('genre', 5250)

user_id       1                              2              3            4  \
0    5250                                                                      
1    5250  Portal  The Binding of Isaac: Rebirth  Left 4 Dead 2  Psychonauts   

                          5                       6                  7  \
0                                                                        
1  Ori and the Blind Forest  Counter-Strike: Source  BioShock Infinite   

          8                                     9  ...  \
0                                                  ...   
1  Mafia II  Vampire: The Masquerade - Bloodlines  ...   

                                 11               12  \
0                                                      
1  Call of Duty® 4: Modern Warfare®  Killing Floor 2   

                                 13                          14  \
0                                                                 
1  Call of Duty®: Modern Warfare® 2  Wolfenstein: The New Order   

                            15                               16  \
0                                                                 
1  Call of Duty®: Black Ops II  Tom Clancy's Rainbow Six® Siege   

                17                       18                19  \
0                                                               
1  The Evil Within  Metro: Last Light Redux  Metro 2033 Redux   

                                 20  
0                                    
1  Call of Duty®: Modern Warfare® 3  

[2 rows x 21 columns]

In [168]:
make_recommendation_bycolumn('genre_publisher_developer', 5250)

user_id         1              2            3               4  \
0    5250                                                         
1    5250  Portal 2  Left 4 Dead 2  Half-Life 2  Counter-Strike   

                        5          6                         7  \
0                                                                
1  Counter-Strike: Source  Half-Life  Half-Life 2: Episode Two   

                           8            9  ...                     11  \
0                                          ...                          
1  Half-Life: Opposing Force  Left 4 Dead  ...  Half-Life: Blue Shift   

                      12                       13             14  \
0                                                                  
1  Day of Defeat: Source  Half-Life 2: Deathmatch  Day of Defeat   

                      15                  16                 17        18  \
0                                                                           
1  Team Fortress Classic  Deathmatch Classic  Half-Life: Source  Ricochet   

                             19 20  
0                                   
1  Half-Life Deathmatch: Source     

[2 rows x 21 columns]

In [169]:
make_recommendation_bycolumn('genre_popular_tags_developer', 5250)

user_id              1              2              3                4  \
0    5250                                                                 
1    5250  Killing Floor  Left 4 Dead 2  Dead Space™ 2  Team Fortress 2   

         5         6       7                                       8  \
0                                                                      
1  Synergy  Warframe  Arma 3  Earth Defense Force: Insect Armageddon   

                                   9  ...                    11  \
0                                     ...                         
1  Tom Clancy's Rainbow Six® Vegas 2  ...  Halo: Spartan Strike   

                            12                                    13  \
0                                                                      
1  Call of Duty®: Black Ops II  Tom Clancy’s Splinter Cell Blacklist   

                       14              15              16        17  \
0                                                                     
1  Alien Breed 2: Assault  Primal Carnage  ORION: Prelude  Defiance   

                           18        19                 20  
0                                                           
1  Primal Carnage: Extinction  God Mode  Scourge: Outbreak  

[2 rows x 21 columns]

In [186]:
#Function to generate recommendation for 20 users by a column feature
def make_recommendationforNusers(column_name):
    recom_by_userdata = DataFrame(columns=df_new)
    games_data[column_name] = games_data[column_name].fillna('')
    #Calculating Cosine Similarity Matrix using the column feature
    count =  CountVectorizer(stop_words='english')
    count_matrix = count.fit_transform(games_data[column_name])
    similarity_matrix = cosine_similarity(count_matrix, count_matrix)
    id = ''
    count = 0
    suggestion_list = list()
    games_user_has_list = list()
    for i, row in users_data.iterrows():
       if count == 20:
        break
       if row["user_id"] != id:   
         recom_by_userdata = concat([recom_by_userdata, make_recommendation_for_user(id, suggestion_list, games_user_has_list)])  
         id = row["user_id"]
         count += 1
         suggestion_list = list()
         games_user_has_list = list()
       games_user_has_list.extend([row["game"]])
       suggestion_list.extend(make_recommendation_by_sim(row["game"], similarity_matrix))
    recom_by_userdata = concat([recom_by_userdata, make_recommendation_for_user(id, suggestion_list, games_user_has_list)], ignore_index=True)
    return recom_by_userdata, similarity_matrix

In [191]:
df_genre, genre_matrix = make_recommendationforNusers('genre')
df_genre

user_id                                 1  \
0                                                
1     5250.0                            Portal   
2    76767.0                            Portal   
3    86540.0                          Portal 2   
4   103360.0                            Portal   
5   144736.0                            Portal   
6   181212.0                            Portal   
7   229911.0                            Portal   
8   298950.0                          Portal 2   
9   299153.0                            Portal   
10  381543.0                            Portal   
11  547685.0     The Binding of Isaac: Rebirth   
12  554278.0     The Binding of Isaac: Rebirth   
13  561758.0  Keep Talking and Nobody Explodes   
14  577614.0                            Portal   
15  604988.0                            Portal   
16  622362.0                            Portal   
17  635733.0                            Portal   
18  683019.0                            Portal   
19  714122.0                            Portal   
20  748719.0           Cook, Serve, Delicious!   

                                        2                                   3  \
0                                                                               
1           The Binding of Isaac: Rebirth            Ori and the Blind Forest   
2                               Primordia                            The Room   
3   Grim Legends 2: Song of the Dark Swan           The Witcher® 3: Wild Hunt   
4           The Binding of Isaac: Rebirth                       Left 4 Dead 2   
5           The Binding of Isaac: Rebirth                       Left 4 Dead 2   
6           The Binding of Isaac: Rebirth                       Left 4 Dead 2   
7           The Binding of Isaac: Rebirth            Ori and the Blind Forest   
8        fault - milestone two side:above  Castle Crashers - Pink Knight Pack   
9           The Binding of Isaac: Rebirth                       Left 4 Dead 2   
10          The Binding of Isaac: Rebirth                       Left 4 Dead 2   
11                                 Portal                         Psychonauts   
12                                 Portal                         Psychonauts   
13                                   Hook         Defense Grid: The Awakening   
14          The Binding of Isaac: Rebirth                       Left 4 Dead 2   
15          The Binding of Isaac: Rebirth                       Left 4 Dead 2   
16          The Binding of Isaac: Rebirth            Ori and the Blind Forest   
17          The Binding of Isaac: Rebirth                       Left 4 Dead 2   
18          The Binding of Isaac: Rebirth            Ori and the Blind Forest   
19          The Binding of Isaac: Rebirth                       Left 4 Dead 2   
20                           Door Kickers         Arma 2: Operation Arrowhead   

                                                    4  \
0                                                       
1                                       Left 4 Dead 2   
2                       The Binding of Isaac: Rebirth   
3   Freddi Fish 4: The Case of the Hogfish Rustler...   
4                                         Psychonauts   
5                                         Psychonauts   
6                                         Psychonauts   
7                  Supreme Commander: Forged Alliance   
8                    Keep Talking and Nobody Explodes   
9                                         Psychonauts   
10                                        Psychonauts   
11                           Ori and the Blind Forest   
12                           Ori and the Blind Forest   
13                      The Binding of Isaac: Rebirth   
14                                        Psychonauts   
15                                        Psychonauts   
16                                      Left 4 Dead 2   
17                                        Psychonauts   
18                                    

In [192]:
print(genre_matrix)

[[1.         0.56694671 0.75592895 ... 0.         0.         0.2236068 ]
 [0.56694671 1.         0.85714286 ... 0.21821789 0.37796447 0.16903085]
 [0.75592895 0.85714286 1.         ... 0.         0.         0.16903085]
 ...
 [0.         0.21821789 0.         ... 1.         0.57735027 0.        ]
 [0.         0.37796447 0.         ... 0.57735027 1.         0.        ]
 [0.2236068  0.16903085 0.16903085 ... 0.         0.         1.        ]]


In [194]:
df_tags, tag_matrix = make_recommendationforNusers('popular_tags')
df_tags

user_id                                            1  \
0                                                           
1     5250.0           Battlefield: Bad Company 2 Vietnam   
2    76767.0    The Witcher 3: Wild Hunt - Expansion Pass   
3    86540.0           Battlefield: Bad Company 2 Vietnam   
4   103360.0           Battlefield: Bad Company 2 Vietnam   
5   144736.0           Battlefield: Bad Company 2 Vietnam   
6   181212.0           Battlefield: Bad Company 2 Vietnam   
7   229911.0           Battlefield: Bad Company 2 Vietnam   
8   298950.0    The Witcher 3: Wild Hunt - Expansion Pass   
9   299153.0           Battlefield: Bad Company 2 Vietnam   
10  381543.0           Battlefield: Bad Company 2 Vietnam   
11  547685.0           Battlefield: Bad Company 2 Vietnam   
12  554278.0           Battlefield: Bad Company 2 Vietnam   
13  561758.0           Battlefield: Bad Company 2 Vietnam   
14  577614.0           Battlefield: Bad Company 2 Vietnam   
15  604988.0  Unreal Tournament: Game of the Year Edition   
16  622362.0           Battlefield: Bad Company 2 Vietnam   
17  635733.0           Battlefield: Bad Company 2 Vietnam   
18  683019.0  Unreal Tournament: Game of the Year Edition   
19  714122.0  Unreal Tournament: Game of the Year Edition   
20  748719.0                    Tom Clancy's Ghost Recon®   

                                               2  \
0                                                  
1                                         Portal   
2             Battlefield: Bad Company 2 Vietnam   
3                      The Witcher® 3: Wild Hunt   
4    Unreal Tournament: Game of the Year Edition   
5    Unreal Tournament: Game of the Year Edition   
6                                         Portal   
7                                         Portal   
8                                       Portal 2   
9                                         Portal   
10   Unreal Tournament: Game of the Year Edition   
11   Unreal Tournament: Game of the Year Edition   
12                                        Portal   
13  planetarian ~the reverie of a little planet~   
14   Unreal Tournament: Game of the Year Edition   
15     Serious Sam Classic: The Second Encounter   
16   Unreal Tournament: Game of the Year Edition   
17   Unreal Tournament: Game of the Year Edition   
18     Serious Sam Classic: The Second Encounter   
19                                       Descent   
20                 Just Cause 2: Multiplayer Mod   

                                              3  \
0                                                 
1                          BattleBlock Theater®   
2   Unreal Tournament: Game of the Year Edition   
3                               The Expendabros   
4                                 Killing Floor   
5                                   Half-Life 2   
6   Unreal Tournament: Game of the Year Edition   
7   Unreal Tournament: Game of the Year Edition   
8                              Tetrobot and Co.   
9   Unreal Tournament: Game of the Year Edition   
10                                      Descent   
11                                      Descent   
12  Unreal Tournament: Game of the Year Edition   
13                         BattleBlock Theater®   
14                                Killing Floor   
15                                      Descent   
16                                      Descent   
17                                Killing Floor   
18                                  Half-Life 2   
19    Serious Sam Classic: The Second Encounter   
20                  Arma 2: Operation Arrowhead   

                                              4  \
0                                                 
1   Unreal Tournament: Game of the Year Edition   
2                          BattleBlock Theater®   
3           Enigmatis 2: The Mists of Ravenwood   
4     Serious Sam Classic: The Second Encounter   
5     Serious Sam Classic: The Second Encounter   
6                                    

In [195]:
print(tag_matrix)

[[1.         0.40022241 0.38100038 ... 0.17038855 0.10369517 0.14664712]
 [0.40022241 1.         0.52522573 ... 0.11744404 0.10721125 0.15161961]
 [0.38100038 0.52522573 1.         ... 0.02795085 0.         0.14433757]
 ...
 [0.17038855 0.11744404 0.02795085 ... 1.         0.27386128 0.        ]
 [0.10369517 0.10721125 0.         ... 0.27386128 1.         0.        ]
 [0.14664712 0.15161961 0.14433757 ... 0.         0.         1.        ]]


In [196]:
df_gen_pub_dev, gen_pub_dev_matrix = make_recommendationforNusers('genre_publisher_developer')
df_gen_pub_dev

user_id                                               1  \
0                                                              
1     5250.0                                          Portal   
2    76767.0                                          Portal   
3    86540.0                                        Portal 2   
4   103360.0                                        Portal 2   
5   144736.0                                        Portal 2   
6   181212.0                                        Portal 2   
7   229911.0                                        Portal 2   
8   298950.0  Ori and the Blind Forest (Original Soundtrack)   
9   299153.0                                        Portal 2   
10  381543.0                                        Portal 2   
11  547685.0                                        Portal 2   
12  554278.0                                        Portal 2   
13  561758.0              Battlefield: Bad Company 2 Vietnam   
14  577614.0                                        Portal 2   
15  604988.0                                        Portal 2   
16  622362.0                                        Portal 2   
17  635733.0                                        Portal 2   
18  683019.0                                        Portal 2   
19  714122.0                                        Portal 2   
20  748719.0                     Arma 2: Operation Arrowhead   

                                   2                              3  \
0                                                                     
1                      Left 4 Dead 2         Counter-Strike: Source   
2                        Half-Life 2  The Journey Down: Chapter Two   
3   Sam & Max 102: Situation: Comedy              The Wolf Among Us   
4                      Left 4 Dead 2                    Half-Life 2   
5                      Left 4 Dead 2                    Half-Life 2   
6                      Left 4 Dead 2                 Counter-Strike   
7                      Left 4 Dead 2         Counter-Strike: Source   
8   Keep Talking and Nobody Explodes                       Portal 2   
9                      Left 4 Dead 2         Counter-Strike: Source   
10                     Left 4 Dead 2                    Half-Life 2   
11                     Left 4 Dead 2                   Kingdom Rush   
12            Mount & Blade: Warband                  Left 4 Dead 2   
13  Keep Talking and Nobody Explodes         Mount & Blade: Warband   
14                     Left 4 Dead 2                    Half-Life 2   
15                     Left 4 Dead 2                    Half-Life 2   
16                       Half-Life 2                  Left 4 Dead 2   
17                     Left 4 Dead 2                    Half-Life 2   
18                     Left 4 Dead 2                    Half-Life 2   
19                     Left 4 Dead 2                    Half-Life 2   
20            ARMA: Cold War Assault   Arma 2: British Armed Forces   

                                       4                                   5  \
0                                                                              
1               Half-Life 2: Episode Two                         Left 4 Dead   
2                 Euro Truck Simulator 2                       Left 4 Dead 2   
3             Sam & Max 105: Reality 2.0                       Hotline Miami   
4                 Counter-Strike: Source            Half-Life 2: Episode Two   
5                 Counter-Strike: Source            Half-Life 2: Episode Two   
6                 Counter-Strike: Source            Half-Life 2: Episode Two   
7               Half-Life 2: Episode Two           Half-Life: Opposing Force   
8                 One Finger Death Punch  Battlefield: Bad Company 2 Vietnam   
9               Half-Life 2: Episode Two                         Left 4 Dead   
10                Counter-Strike: Source            Half-Life 2: Episode Two   
11            GemCraft - Chasing Shadows                         Half-Lif

In [197]:
print(gen_pub_dev_matrix)

[[1.         0.2236068  0.25354628 ... 0.         0.         0.12909944]
 [0.2236068  1.         0.47245559 ... 0.         0.         0.14433757]
 [0.25354628 0.47245559 1.         ... 0.         0.         0.10910895]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.12909944 0.14433757 0.10910895 ... 0.         0.         1.        ]]


In [198]:
df_tags_dev_gen, tags_dev_gen_matrix = make_recommendationforNusers('genre_popular_tags_developer')
df_tags_dev_gen

user_id                                            1  \
0                                                           
1     5250.0           Battlefield: Bad Company 2 Vietnam   
2    76767.0           Battlefield: Bad Company 2 Vietnam   
3    86540.0                                     Portal 2   
4   103360.0           Battlefield: Bad Company 2 Vietnam   
5   144736.0           Battlefield: Bad Company 2 Vietnam   
6   181212.0           Battlefield: Bad Company 2 Vietnam   
7   229911.0           Battlefield: Bad Company 2 Vietnam   
8   298950.0    The Witcher 3: Wild Hunt - Expansion Pass   
9   299153.0           Battlefield: Bad Company 2 Vietnam   
10  381543.0           Battlefield: Bad Company 2 Vietnam   
11  547685.0           Battlefield: Bad Company 2 Vietnam   
12  554278.0           Battlefield: Bad Company 2 Vietnam   
13  561758.0           Battlefield: Bad Company 2 Vietnam   
14  577614.0           Battlefield: Bad Company 2 Vietnam   
15  604988.0  Unreal Tournament: Game of the Year Edition   
16  622362.0           Battlefield: Bad Company 2 Vietnam   
17  635733.0           Battlefield: Bad Company 2 Vietnam   
18  683019.0  Unreal Tournament: Game of the Year Edition   
19  714122.0  Unreal Tournament: Game of the Year Edition   
20  748719.0                       Mount & Blade: Warband   

                                              2  \
0                                                 
1                          BattleBlock Theater®   
2                        Mount & Blade: Warband   
3            Battlefield: Bad Company 2 Vietnam   
4   Unreal Tournament: Game of the Year Edition   
5   Unreal Tournament: Game of the Year Edition   
6   Unreal Tournament: Game of the Year Edition   
7   Unreal Tournament: Game of the Year Edition   
8            Battlefield: Bad Company 2 Vietnam   
9   Unreal Tournament: Game of the Year Edition   
10  Unreal Tournament: Game of the Year Edition   
11  Unreal Tournament: Game of the Year Edition   
12  Unreal Tournament: Game of the Year Edition   
13                 Everyday Genius: SquareLogic   
14  Unreal Tournament: Game of the Year Edition   
15                       Counter-Strike: Source   
16  Unreal Tournament: Game of the Year Edition   
17  Unreal Tournament: Game of the Year Edition   
18                                  Half-Life 2   
19                                  Half-Life 2   
20                Just Cause 2: Multiplayer Mod   

                                            3  \
0                                               
1   Serious Sam Classic: The Second Encounter   
2                             The Expendabros   
3         Enigmatis 2: The Mists of Ravenwood   
4                                 Half-Life 2   
5                                 Half-Life 2   
6                              Counter-Strike   
7                      Counter-Strike: Source   
8                                    Portal 2   
9                      Counter-Strike: Source   
10                                Half-Life 2   
11                                Half-Life 2   
12                     Counter-Strike: Source   
13                       BattleBlock Theater®   
14                     Counter-Strike: Source   
15                            Quake III Arena   
16                                Half-Life 2   
17                                Half-Life 2   
18                     Counter-Strike: Source   
19                     Counter-Strike: Source   
20                Arma 2: Operation Arrowhead   

                                              4  \
0                                                 
1                                 Left 4 Dead 2   
2                          BattleBlock Theater®   
3                                      The Room   
4                        Counter-Strike: Source   
5                        Counter-Strike: Source   
6                                         QUAKE   
7                      Half-Life 2: Episode Two   
8

In [199]:
print(tags_dev_gen_matrix)

[[1.         0.44378474 0.53293871 ... 0.12209657 0.         0.24019223]
 [0.44378474 1.         0.68774638 ... 0.08897681 0.         0.21879749]
 [0.53293871 0.68774638 1.         ... 0.02114775 0.         0.20801257]
 ...
 [0.12209657 0.08897681 0.02114775 ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.24019223 0.21879749 0.20801257 ... 0.         0.         1.        ]]
